# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='noise',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
